name: Update production server
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: get latest docker image version tag
        id: get_latest_tag
        run: |
          cd ~/app/informations.wolfdefansy.org
          docker-compose pull && docker-compose down && docker-compose up -d